added an endpoint to profitability index using annual cash flows
Clueless-Community/fintech-api pull request #164
Opened 2023-01-03 11:51 UTC by ShamanthVallem

For issue #146 
changes made:
1) Created an endpoint to calculate profitability endpoint using annual cash flows

2023-01-04 06:14 UTC, nikhil25803 commented
Hey @ShamanthVallem, there are some merge conflicts, please do resolve them first,

2023-01-04 11:57 UTC, ShamanthVallem commented
@nikhil25803 I resolved all merge conflicts.

2023-01-05 14:03 UTC, nikhil25803 requested changes
Requested some changes, please look into it.

2023-01-05 14:03 UTC, nikhil25803 commented on ENDPOINTS.md
> +    "discount_rate" : 10%,
Case the `discount_rate` into a string, and `profitability_index` without any dollar or sign.

2023-01-05 18:08 UTC, merged

2023-01-06 15:40 UTC, ShamanthVallem commented
@nikhil25803 Points were not awarded for this PR, can u please check

2023-01-06 16:50 UTC, nikhil25803 commented
> @nikhil25803 I did not receive points for this Pull request, can u please check

Codepeak is wrapped up now, no points will be reflected in the leaderboard anymore.