Added market order function
Clueless-Community/fintech-api pull request #346
Opened 2023-06-13 16:46 UTC by Abhinavcode13

Added the function

2023-06-13 16:46 UTC, Abhinavcode13 commented
Please check now @ighoshsubho

2023-06-14 16:08 UTC, ighoshsubho commented
The logic is commented in the main.py file

2023-06-14 17:23 UTC, Abhinavcode13 commented
@ighoshsubho updated it :)

2023-06-15 12:38 UTC, Abhinavcode13 commented
@ighoshsubho check once again

2023-06-15 14:35 UTC, ighoshsubho commented on helpers/functions.py
> +        execute_buy_order(symbol, current_price, quantity)  # Function to execute a buy order
Where is execute_buy_order function??

2023-06-17 17:57 UTC, nikhil25803 requested changes
Make some required changes and do upload a SS of the endpoint response next time as well.

2023-06-17 17:57 UTC, nikhil25803 commented on helpers/functions.py
> +        print(f"Invalid order type: {order_type}")
Instead of printing the value, do return the response so that it can be used elsewhere.

2023-06-17 17:57 UTC, nikhil25803 commented on main.py
> +        return {
You are just accepting the values and returning the same value without any processing and calculation.

2023-06-30 03:46 UTC, ighoshsubho commented
Please check the CONTRIBUTIONS.md and make a fresh PR

2023-06-30 14:29 UTC, closed without merging